apiVersion: v1
kind: ReplicationController 
metadata:
 name: mylogin-rc
spec: 
 replicas: 4
 selector: 
   app: mylogin 
   version: 2.6.2
 template:
  metadata: 
   labels: 
     app: mylogin 
     version: 2.6.2
  spec:
   containers:
     - name: mylogin-container
       image: kingsuresh/myjavaapp08jun:1
       ports: 
         - containerPort: 8080